# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

silent: true

tasks:
  format:
    desc: Formats Go code
    cmd: go fmt ./...

  lint:
    desc: Lints Go code
    cmd: go vet ./...

  check:
    desc: Formats and lints Go code
    cmd: task format lint
